### ISSUE TITLE
gke-notebook: spawning kernel failed

### ISSUE THREAD

**Issue by rainwoodman** [GoogleCloudPlatform/ai-notebooks-extended#1]
Hi,

I followed the steps at https://cloud.google.com/solutions/spawning-notebook-servers-on-gke-tutorial to setup the jupyter hub on GKE. After the step getting the URL, I was able to connect to the hub. However when I launch my kernel it fails:

1. If I select the basic kernel, it fails with:
```
Server requested
2020-12-02T00:30:51Z [Normal] Successfully assigned default/jupyter-feyu to XXXXXXXXXXXXXXXXXXXXX
2020-12-02T00:30:51Z [Normal] Container image "gcr.io/XXXXXXXXXXX/jupyter-mine-basic" already present on machine
2020-12-02T00:30:51Z [Normal] Created container notebook
2020-12-02T00:30:51Z [Normal] Started container notebook
Spawn failed: Server at http://XXXXXXXX:8080/user/feyu/ didn't respond in 30 seconds
```

2. If I select the tf2 kernel, the singluser server is launched, but I get a page not found (404) error on /user/feyu.

It seems like for 1), the issue is the docker image was misconfigured (e.g. the path to binary is incorrect?)
for 2), the user dispatch proxy of jupyterhub may be misconfigured. (Perhaps something wrong with the kubenates launcher)

However, I am quite new to GKE and at this point I don't know where to look for logs to debug this further. Any suggestions?

Thanks!

**Comment by m-mayran** [comment]
For 1, I am not sure. It should work, you built your own image in your project registry I suppose? I'll have to run through it e2e again to see why it's failing.
For 2, it's my bad. I never removed this image. I need to convert an AI Platform Notebooks docker image to a working image for this platform.

**Comment by rainwoodman** [comment]
1: Yes. I ran script number 15 to build the image. 

I fiddled around and found  `kubectl logs jupyter-feyu` shows the log before kubespanwer terminates the pod.  I was able to catch a permission error in the log about lack of access to jupyter_notebook_config.py. The Dockerfile may need some tweaking?

2: Thanks for the info. Would you mind explaining the main difference between an image for AI platform and here?

**Comment by rainwoodman** [comment]
I figured how to 'ssh' into a kube pod and was able to track down the error to a simple permission error. PR filed!
