### ISSUE TITLE
35-use-wid.sh: line 16: ../manifests/overlays/gke-wi/agent-deployment.yaml: No such file or directory

### ISSUE THREAD

**Issue by timretout** [GoogleCloudPlatform/ai-notebooks-extended#4]
When attempting to run the GKE Hub example with Workload Identity enabled (i.e. setting WID="true" in 10-set-variables.sh) I hit this error:
```
35-use-wid.sh: line 16: ../manifests/overlays/gke-wi/agent-deployment.yaml: No such file or directory
```
and then:
```
error: the path "../manifests/overlays/gke-wi/agent-deployment.yaml" does not exist
35-use-wid.sh: line 61: ../manifests/overlays/gke-wi/patch_gke.yaml: No such file or directory
```

The code seems to expect the directory "manifests/overlays/gke-wi" to exist, but it isn't currently committed.  Have I missed a step, or are the files missing? Thanks!

**Comment by m-mayran** [comment]
I just merged a PR and push some minor fixes. See if you still see the b/

Note that if you see a 500, for now refresh the page and it should work. I'll open a b/ to look into it later.

**Comment by timretout** [comment]
Yep, fixed. I don't see this error any more, and Workload Identity is enabled on the cluster by default.
